# Permalinks
permalink:        pretty

# Setup
url:              http://anchietajunior.github.io

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          /anchietajunior.github.io

title:            Anchieta Júnior

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  A simple Blog for learn and share content about Ruby on Rails, Front-end, Javascript and its tools.

# The tags listed as entries in the sidebar
sidebar_tags:     [jekyll, hyde]

# Fallback image and color if not overwritten for tag or post
image:            /anchietajunior.github.io/public/img/nap.jpg
color:            '#A85641'

author:
  name:           'Anchieta Júnior'

  # Setting social media usernames will add icons at the bottom of the sidebar
  twitter:        anchietajr87
  github:         anchietajunior

  # Setting a disqus username will enable the comment section
  disqus:         qwtel

  # This photo will be used in the about section
  photo:          http://qwtel.com/public/img/flo.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    Olá, desenvolvo pra web desde 2006, mas a 2 anos que realmente estou ativo na comunidade Ruby on Rails
    e front-end.

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
